version: '3'

services:

  app:
    build:
      context: .
    environment:
      DB_HOSTNAME: database
      DB_DATABASE: news
      DB_USERNAME: news
      DB_PASSWORD: charizard
      DB_TIMEZONE: Australia/Sydney
    networks: 
      - app-network
    ports:
      - "3100:3100"

  database:
    image: mariadb:latest
    environment:
      MYSQL_DATABASE: news
      MYSQL_USER: news
      MYSQL_PASSWORD: charizard
      MYSQL_ROOT_PASSWORD: root
    networks: 
      - app-network
    volumes:
      - db-data:/var/lib/mysql

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
    driver: local