version: '3'

services:

  app:
    build:
      context: .
    environment:
      WEB_PORT: 3100
      DB_HOSTNAME: database
      DB_DATABASE: news
      DB_USERNAME: news
      DB_PASSWORD: charizard
      DB_TIMEZONE: Australia/Sydney
      QUERY_LIMIT: 10
      QUERY_KEY: key
    networks: 
      - app-network
    ports:
      - "3100:3100"
    depends_on:
      - database

  database:
    image: mariadb:latest
    environment:
      MYSQL_DATABASE: news
      MYSQL_USER: news
      MYSQL_PASSWORD: charizard
      MYSQL_ROOT_PASSWORD: root
    networks: 
      - app-network
    volumes:
      - ./data:/var/lib/mysql

networks:
  app-network:
    driver: bridge
